version: "3.9"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/svm_sign_model.pkl:/app/svm_sign_model.pkl:ro
      - ./frontend:/app/../frontend:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: unless-stopped
